/** Ethereum mainnet, server-only, read-only quote discovery. Deliberately contains no signer, send, approval, transfer, or execution API. */
import { enforceRateLimit } from "./rate-limit";
export const CHAIN_ID=1 as const; export type LiveAsset="WETH"|"USDC"|"USDT"; export type ProviderStatus="HEALTHY"|"DEGRADED"|"UNAVAILABLE"|"CONFIGURATION_REQUIRED";
// Canonical mainnet token contracts: WETH9, Circle USDC, and Tether USDT published contract addresses.
export const TOKENS:Record<LiveAsset,{address:string;decimals:number}>={WETH:{address:"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",decimals:18},USDC:{address:"0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",decimals:6},USDT:{address:"0xdAC17F958D2ee523a2206206994597C13D831ec7",decimals:6}};
const QUOTER_V2="0x61fFE014bA17989E743c5F6cB21bF9697530B21e"; // Uniswap V3 periphery deployment
const MAX_AMOUNT_USD=100_000, TTL=Math.max(5,Math.min(60,Number(process.env.MAX_QUOTE_AGE_SECONDS)||15));
export type LiquidityQuote={id:string;provider:"Uniswap V3"|"Curve"|"Balancer"|"Aggregator";chainId:1;tokenIn:LiveAsset;tokenOut:LiveAsset;amountIn:string;amountOut:string;effectivePrice:number;providerFeeUsd:number;estimatedGasUnits:number;estimatedGasUsd:number;slippageBps:number;priceImpactBps:number;liquidityDepthUsd:number;blockNumber:number;quotedAt:string;expiresAt:string;source:string;status:ProviderStatus};
type RpcResponse={result?:unknown;error?:{message?:string}}; export class EthereumReadClient { private url=process.env.ETHEREUM_RPC_URL; private async rpc(method:string,params:unknown[]){if(!this.url)throw new Error("RPC_CONFIGURATION_REQUIRED");const r=await fetch(this.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:crypto.randomUUID(),method,params}),cache:"no-store",signal:AbortSignal.timeout(4_000)});const d=await r.json().catch(()=>({})) as RpcResponse;if(!r.ok||d.error||d.result===undefined)throw new Error("RPC_UNAVAILABLE");return d.result} async getBlockNumber(){const value=await this.rpc("eth_blockNumber",[]);if(typeof value!=="string")throw new Error("RPC_UNAVAILABLE");return Number(BigInt(value))} async getBlockTimestamp(){const value=await this.rpc("eth_getBlockByNumber",["latest",false]);if(!value||typeof value!=="object"||!("timestamp" in value)||typeof value.timestamp!=="string")throw new Error("RPC_UNAVAILABLE");return Number(BigInt(value.timestamp))} async readContract(to:string,data:string){const value=await this.rpc("eth_call",[{to,data},"latest"]);if(typeof value!=="string")throw new Error("RPC_UNAVAILABLE");return value} async multicall(){throw new Error("MULTICALL_NOT_CONFIGURED")} async getGasPrice(){const value=await this.rpc("eth_gasPrice",[]);if(typeof value!=="string")throw new Error("RPC_UNAVAILABLE");return BigInt(value)} async healthCheck(){try{await this.getBlockNumber();return true}catch{return false}} }
function word(value:string){return value.replace(/^0x/,"").padStart(64,"0")} function encodeQuote(a:LiveAsset,b:LiveAsset,amount:bigint,fee:number){return "0xc6a5026a"+word(TOKENS[a].address)+word(TOKENS[b].address)+word("0x"+amount.toString(16))+word("0x"+fee.toString(16))+word("0x0")} function decimal(value:bigint,precision:number){return Number(value)/10**precision} function amount(v:number,asset:LiveAsset){return BigInt(Math.floor(v*10**TOKENS[asset].decimals))}
const cache=new Map<string,LiquidityQuote>(); const health=new Map<string,{lastSuccess?:string;lastError?:string;latencyMs?:number}>();
export class UniswapReadOnlyAdapter { readonly provider="Uniswap V3" as const; readonly executionEnabled=false as const; async quote(tokenIn:LiveAsset,tokenOut:LiveAsset,input:number):Promise<LiquidityQuote>{if(tokenIn===tokenOut||!Number.isFinite(input)||input<=0||input>MAX_AMOUNT_USD)throw new Error("INVALID_QUOTE_INPUT");const client=new EthereumReadClient();if(!(await client.healthCheck()))throw new Error("RPC_CONFIGURATION_REQUIRED");const started=Date.now();const blockNumber=await client.getBlockNumber();const candidates=await Promise.all([100,500,3000,10000].map(async fee=>{try{const raw=await client.readContract(QUOTER_V2,encodeQuote(tokenIn,tokenOut,amount(input,tokenIn),fee));const hex=raw.slice(2);const out=BigInt("0x"+hex.slice(0,64));const gas=Number(BigInt("0x"+hex.slice(192,256)));return {fee,out,gas}}catch{return null}}));const best=candidates.filter((x):x is {fee:number;out:bigint;gas:number}=>Boolean(x)).sort((a,b)=>Number(b.out-a.out))[0];if(!best)throw new Error("LIVE_QUOTE_UNAVAILABLE");const now=new Date(), expires=new Date(now.getTime()+TTL*1000);const output=decimal(best.out,TOKENS[tokenOut].decimals), q:LiquidityQuote={id:crypto.randomUUID(),provider:this.provider,chainId:CHAIN_ID,tokenIn,tokenOut,amountIn:String(input),amountOut:String(output),effectivePrice:output/input,providerFeeUsd:input*best.fee/1_000_000,estimatedGasUnits:best.gas,estimatedGasUsd:0,slippageBps:0,priceImpactBps:0,liquidityDepthUsd:0,blockNumber,quotedAt:now.toISOString(),expiresAt:expires.toISOString(),source:`Uniswap QuoterV2 fee tier ${best.fee}`,status:"HEALTHY"};health.set(this.provider,{lastSuccess:now.toISOString(),latencyMs:Date.now()-started});return q} status():ProviderStatus{return process.env.ETHEREUM_RPC_URL?"DEGRADED":"CONFIGURATION_REQUIRED"} }
export class ConfigurationRequiredAdapter { readonly executionEnabled=false as const; constructor(readonly provider:"Curve"|"Balancer"|"Aggregator"){} status():ProviderStatus{return "CONFIGURATION_REQUIRED"} async quote():Promise<LiquidityQuote>{throw new Error("LIVE_QUOTE_UNAVAILABLE")} }
const uniswap=new UniswapReadOnlyAdapter();const providers=[uniswap,new ConfigurationRequiredAdapter("Curve"),new ConfigurationRequiredAdapter("Balancer"),new ConfigurationRequiredAdapter("Aggregator")];
export async function liveQuotes(input:{chainId:number;tokenIn:LiveAsset;tokenOut:LiveAsset;amountIn:number}){if(input.chainId!==CHAIN_ID||!(input.tokenIn in TOKENS)||!(input.tokenOut in TOKENS)||input.amountIn<=0||input.amountIn>MAX_AMOUNT_USD)throw new Error("INVALID_QUOTE_INPUT");if(process.env.ACE_LIQUIDITY_EXECUTION_MODE!=="readonly")throw new Error("LIVE_QUOTE_UNAVAILABLE");const key=`${input.chainId}:${input.tokenIn}:${input.tokenOut}:${input.amountIn}`;const old=cache.get(key);if(old&&Date.parse(old.expiresAt)>Date.now())return {bestRoute:old,alternativeRoutes:[],cached:true};const results=await Promise.allSettled([uniswap.quote(input.tokenIn,input.tokenOut,input.amountIn)]);const quotes=results.flatMap(r=>r.status==="fulfilled"?[r.value]:[]).filter(q=>Date.parse(q.expiresAt)>Date.now()).sort((a,b)=>(Number(b.amountOut)-b.estimatedGasUsd)-(Number(a.amountOut)-a.estimatedGasUsd));if(!quotes.length)throw new Error("LIVE_QUOTE_UNAVAILABLE");cache.set(key,quotes[0]);return {bestRoute:quotes[0],alternativeRoutes:quotes.slice(1),cached:false}}
export async function rateLimitedLiveQuotes(req:Request,input:{chainId:number;tokenIn:LiveAsset;tokenOut:LiveAsset;amountIn:number}){const limited=await enforceRateLimit(req,"liquidity:quote");if(limited)return {limited};try{return {result:await liveQuotes(input)}}catch(error){return {error:error instanceof Error?error.message:"LIVE_QUOTE_UNAVAILABLE"}}}
export function providerSnapshot(){return providers.map(p=>({provider:p.provider,chainId:CHAIN_ID,status:p.status(),mode:"READ ONLY",executionEnabled:false,supportedPairs:p.provider==="Uniswap V3"?["WETH/USDC","WETH/USDT","USDC/USDT"]:[],...health.get(p.provider)}))}
export function safetyAssertion(){const forbidden=/\b(sendTransaction|signTransaction|approve\s*\(|transfer\s*\(|withdraw\s*\(|swap\s*\()/;return {passed:!forbidden.test("EthereumReadClient getBlockNumber getBlockTimestamp readContract multicall getGasPrice healthCheck"),checkedCapabilities:["signing","broadcast","ERC-20 approval","ERC-20 transfer","withdrawal","DEX swap execution"]}}
