/** TEMPORARY: Preview-only V4A validation. All mutation probes run inside ROLLBACK transactions. */
import { createHmac, timingSafeEqual } from "node:crypto";
import { Pool } from "pg";
const branch="vercel-agent/ace-financial-foundation-v4a";
type Result={pass:boolean;detail?:string};const pass=(detail?:string):Result=>({pass:true,detail}),fail=(detail:string):Result=>({pass:false,detail});
function gate(signature:string|null){const secret=process.env.ACE_V4A_VALIDATION_SECRET;if(process.env.VERCEL_ENV!=="preview"||process.env.VERCEL_GIT_COMMIT_REF!==branch||process.env.ACE_V4A_VALIDATION_ENABLED!=="true"||!secret||!signature)return false;const expected=createHmac("sha256",secret).update("v4a-validation").digest("hex");return signature.length===expected.length&&timingSafeEqual(Buffer.from(signature),Buffer.from(expected));}
async function identity(url:string){const pool=new Pool({connectionString:url,max:1});try{const q=await pool.query<{database:string;user:string}>("SELECT current_database() AS database,current_user AS user");return{pass:q.rows[0]?.database==="neondb"&&q.rows[0]?.user==="ace_exchange_runtime",database:q.rows[0]?.database,user:q.rows[0]?.user}}catch{return{pass:false}}finally{await pool.end()}}
async function rollbackProbe(url:string){const pool=new Pool({connectionString:url,max:1}),out:Record<string,Result>={};let c;try{c=await pool.connect();await c.query("BEGIN");const existing=await c.query('SELECT id FROM "user" LIMIT 1');out.userSelect=pass();out.accountSelect=await c.query("SELECT id FROM account LIMIT 1").then(()=>pass()).catch(()=>fail("denied"));out.rolesSelect=await c.query("SELECT role FROM user_roles LIMIT 1").then(()=>pass()).catch(()=>fail("denied"));if(existing.rows[0]){const id=crypto.randomUUID(),userId=existing.rows[0].id;await c.query('INSERT INTO session(id,"expiresAt",token,"userId") VALUES($1,now()+interval \'1 hour\',$2,$3)',[id,crypto.randomUUID(),userId]);await c.query("SELECT id FROM session WHERE id=$1",[id]);await c.query('UPDATE session SET "updatedAt"=now() WHERE id=$1',[id]);await c.query("DELETE FROM session WHERE id=$1",[id]);out.sessionCrud=pass()}else out.sessionCrud=fail("no Better Auth user available");const key=crypto.randomUUID();await c.query("INSERT INTO idempotency_records_financial(scope,key,request_hash) VALUES('validation',$1,'x')",[key]);await c.query("UPDATE idempotency_records_financial SET result_reference='ok',completed_at=now() WHERE scope='validation' AND key=$1",[key]);out.idempotency=pass();for(const table of ["reward_funding_sources_financial","reward_programs_financial","reward_backing_allocations_financial","reward_accruals_financial","reward_claims_financial","reward_claim_reservations_financial","settlement_plans_financial","settlement_routes_financial"])await c.query(`INSERT INTO ${table}(data) VALUES('{}'::jsonb)`);out.financialInserts=pass();await c.query("INSERT INTO financial_audit_events(event_type,actor_user_id,actor_role,entity_type,entity_id) VALUES('validation','system','system','validation',$1)",[key]);out.auditInsert=pass();for(const [table,set] of [["ledger_transactions_financial","transaction_type='x'"],["ledger_entries_financial","amount=1"],["financial_audit_events","event_type='x'"],["audit_events","action='x'"]] as const){out[`${table}Immutable`]=await c.query(`UPDATE ${table} SET ${set} WHERE false`).then(()=>fail("update allowed")).catch(()=>pass("update denied"))}await c.query("ROLLBACK");return out}catch(error){await c?.query("ROLLBACK").catch(()=>undefined);return{probe:fail(error instanceof Error?error.message:"probe failed")} }finally{c?.release();await pool.end()}}
export async function runV4aValidation(signature:string|null){if(!gate(signature))return null;const authUrl=process.env.BETTER_AUTH_DATABASE_URL,financialUrl=process.env.ACE_DATABASE_URL;if(!authUrl||!financialUrl)return{configuration:fail("database URL missing")};const [betterAuth,financialIdentity,probes]=await Promise.all([identity(authUrl),identity(financialUrl),rollbackProbe(financialUrl)]);return{environment:process.env.VERCEL_ENV,branch,databaseIdentity:{betterAuth,financial:financialIdentity},betterAuth,financialTransactions:probes,ledger:{balanced:"not tested: no runtime ledger accounts provisioned"},appendOnly:probes,idempotency:probes.idempotency,webhook:{configuration:Boolean(process.env.ACE_CUSTODY_WEBHOOK_SECRET),notExecuted:"webhook replay probe deferred"},failures:Object.entries(probes).filter(([,v])=>!v.pass).map(([k,v])=>({k,detail:v.detail}))}}
