import type{PoolClient}from"pg";
export type IdempotencyResult={replayed:boolean;resultReference:string|null};
export class FinancialRepository{constructor(private readonly db:PoolClient){}
 async idempotency(scope:string,key:string,requestHash:string):Promise<IdempotencyResult>{const r=await this.db.query<{result_reference:string|null}>("INSERT INTO idempotency_records_financial(scope,key,request_hash) VALUES($1,$2,$3) ON CONFLICT(scope,key) DO NOTHING RETURNING result_reference",[scope,key,requestHash]);if(r.rowCount)return{replayed:false,resultReference:null};const prior=await this.db.query<{result_reference:string|null}>("SELECT result_reference FROM idempotency_records_financial WHERE scope=$1 AND key=$2 FOR UPDATE",[scope,key]);return{replayed:true,resultReference:prior.rows[0]?.result_reference??null}}
 async completeIdempotency(scope:string,key:string,resultReference:string){await this.db.query("UPDATE idempotency_records_financial SET result_reference=$3,completed_at=now() WHERE scope=$1 AND key=$2",[scope,key,resultReference])}
 async audit(eventType:string,actorUserId:string,actorRole:string,entityType:string,entityId:string,metadataSafe:object){await this.db.query("INSERT INTO financial_audit_events(event_type,actor_user_id,actor_role,entity_type,entity_id,metadata_safe) VALUES($1,$2,$3,$4,$5,$6)",[eventType,actorUserId,actorRole,entityType,entityId,metadataSafe])}
 async createFundingSource(values:object){return this.db.query("INSERT INTO reward_funding_sources_financial(data) VALUES($1) RETURNING id",[values])}
 async createRewardProgram(values:object){return this.db.query("INSERT INTO reward_programs_financial(data) VALUES($1) RETURNING id",[values])}
 async createAllocation(values:object){return this.db.query("INSERT INTO reward_backing_allocations_financial(data) VALUES($1) RETURNING id",[values])}
 async createAccrual(values:object){return this.db.query("INSERT INTO reward_accruals_financial(data) VALUES($1) RETURNING id",[values])}
 async createClaim(values:object){return this.db.query("INSERT INTO reward_claims_financial(data) VALUES($1) RETURNING id",[values])}
 async createReservation(values:object){return this.db.query("INSERT INTO reward_claim_reservations_financial(data) VALUES($1) RETURNING id",[values])}
 async createSettlementPlan(values:object){return this.db.query("INSERT INTO settlement_plans_financial(data) VALUES($1) RETURNING id",[values])}
 async createSettlementRoute(values:object){return this.db.query("INSERT INTO settlement_routes_financial(data) VALUES($1) RETURNING id",[values])}
 async postLedger(transactionType:string,reference:string,entries:Array<{accountId:string;direction:"debit"|"credit";amount:string}>){const debit=entries.filter(e=>e.direction==="debit").reduce((n,e)=>n+Number(e.amount),0),credit=entries.filter(e=>e.direction==="credit").reduce((n,e)=>n+Number(e.amount),0);if(!entries.length||debit!==credit)throw Error("LEDGER_IMBALANCE");const tx=await this.db.query<{id:string}>("INSERT INTO ledger_transactions_financial(transaction_type,reference) VALUES($1,$2) RETURNING id",[transactionType,reference]);for(const e of entries)await this.db.query("INSERT INTO ledger_entries_financial(transaction_id,account_id,direction,amount) VALUES($1,$2,$3,$4)",[tx.rows[0].id,e.accountId,e.direction,e.amount]);await this.db.query("SELECT ace_assert_financial_ledger_balanced($1)",[tx.rows[0].id]);return tx.rows[0].id}
 async markWebhookProcessed(provider:string,eventId:string){const r=await this.db.query("INSERT INTO custody_webhook_events(provider,event_id) VALUES($1,$2) ON CONFLICT(provider,event_id) DO NOTHING RETURNING event_id",[provider,eventId]);return Boolean(r.rowCount)}
}
